### ISSUE TITLE
Laggy Application - Followed by Crash

### ISSUE THREAD

**Issue by Benjamoose** [Shadlock0133/music-vibes#3]
Hey there!

When I run the .exe, the window opens, but seems to run incredibly slowly. If I then attempt to click any of the buttons, I can do so only once, before the entire application crashes.

**OS:** Windows 10
**GPU:** GTX 1070
**CPU:** i7-4790K
**RAM:** 16GB

https://user-images.githubusercontent.com/32703517/183002313-ce47ac19-5ce5-4883-b66c-4cb539c3e459.mp4

**Comment by Benjamoose** [comment]
Additional information:

So, it seems that if I launch the application with no toys connected, it drags smoothly. It may be that it only begins to act this way once it detects and lists a toy.

**Comment by Shadlock0133** [comment]
I've made a new release https://github.com/Shadlock0133/music-vibes/releases/tag/v0.1.2
Can you check if problem is still there?

**Comment by Benjamoose** [comment]
Thanks for the quick response!

I just tried the new release that you linked above.

The "laggy window" issue seems to have been fixed, it seems to drag around smoothly now, regardless of what's happening.

Current issues:
- Every so often the app locks up for a moment, leaving the app and toy in whatever it's last state was for about 3-5 seconds.
- Sometimes it never recovers from the above and crashes again.

https://user-images.githubusercontent.com/32703517/183060605-cd13e48c-7007-44fa-8033-cc256052e1a1.mp4

**Comment by Shadlock0133** [comment]
Can you check this one?
[music-vibes.zip](https://github.com/Shadlock0133/music-vibes/files/9268072/music-vibes.zip)

**Comment by Benjamoose** [comment]
So now, the app no longer freezes/desyncs for those moments.

New issues:
- The volume has to be very loud to get the indicator to register the input enough to make an impact, even with the multiplier maxed out.
- Once the first vibration is initiated on the toy. The toy stays on that setting and just vibrates indefinitely, ignoring the audio-to-vibration updates (which is why I was spamming the stop button at the end of the video).

By the way, if there's anything else I can do to help diagnose, I'd be more than happy to. Are there any logs or something I can share? It's why I'm trying to record with audio waveforms and the like. I'm trying to give as much information as possible, but if there's something else that'd be helpful, let me know.

https://user-images.githubusercontent.com/32703517/183068200-b9d943a9-d80b-41a8-b396-22253110af93.mp4

**Comment by Shadlock0133** [comment]
I don't actually have any logging set-up, so these videos are very useful, thank you for sending them!

**Comment by Shadlock0133** [comment]
I've added new "main volume", just be careful with it, as scales much more rapidly compared to individual devices' "multipliers", kinda like real volume does.

As for vibration getting stuck, I'm still not sure why would that be. I need to think about this one.

PS. I've just noticed you have set "Low pass freq." to 2Hz, which would filter almost all (if not all) audio. Try setting it to max.

**Comment by Benjamoose** [comment]
Oh interesting!

I just did a quick check and maxing it out does seem to possibly solve the low volume thing.

What should the default setting be? I must have accidentally adjusted it then not realized, as I didn't realize that it saved the setting on relaunch.

**Comment by Shadlock0133** [comment]
The default is max, which means no filtering.

**Comment by Benjamoose** [comment]
With the filtering adjustment fixing the other non-issue, I can sort of better describe the vibration issue.

So it seems that one of two things happen:

1) Regardless of volume, the toy vibrates at a "base level". So, the moment "Enable" is checked, it starts vibrating regardless of audio input, but will then vibrate "more" on top of that with music playing and the multiplier turned up.

2) Seems random, but sometimes it gets stuck then never recovers. So, in my testing it a song was playing (the one in the videos above), a big vibration was hit for a second, then it stayed there and seemingly stopped responding to audio input from that point onwards.

_**Edit:** Sorry for making your life hell, haha. But you truly have the best software for this. The only other thing I'd seen was way over-produced and a file dump for what it was. Your app is simple, versatile and low impact space-wise._

**Comment by Benjamoose** [comment]
Hmm, I was able to run the app with no issues a moment ago. 

I'll do some more testing over today and report back.
